backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'teachers'
    label: 'Преподавателям'
    folder: 'content/teachers'
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Тело', name: 'body', widget: 'markdown' }
  - name: 'students'
    label: 'Студентам'
    folder: 'content/students'
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Тело', name: 'body', widget: 'markdown' }
  - name: 'achievements'
    label: 'Достижения'
    folder: 'content/achiements'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Тело', name: 'body', widget: 'markdown' }
  - name: 'news'
    label: 'Новости'
    folder: 'content/news'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Тело', name: 'body', widget: 'markdown' }
  - name: gallery 
    label: 'Галерея'
    folder: 'content/gallery'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Тело', name: 'body', widget: 'markdown' }
